name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories, community, metadata
          base_indepth: yes
          plugin_lines: yes
          plugin_stargazers: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, less, scss, sass
          plugin_languages_skipped: lowlighter/metrics
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_calendar: yes
          plugin_calendar_limit: 2
          plugin_traffic: yes
          
